### ISSUE TITLE
Population Size should be numeric, not string.

### ISSUE THREAD

**Issue by jonovik** [cjbattey/driftR#2]
As of revision 62dfe80, setting e.g. `Population Size = 40` and clicking `Run Simulation` gives the error

    Please select n <= 100,000

This is caused by using `textInput` instead of `numericInput` in ui.R line 14. The reason the default value of `"100"` works is that

```
> "100" <= 100000
[1] TRUE
> "50" <= 100000
[1] FALSE
```

where the right-hand size gets coerced to string for comparison.

I'll send a pull request shortly.

**Comment by cjbattey** [comment]
Thanks for pointing this out. Pop size uses textInput because I want the user to be able to type in a space or comma separated list to run multiple populations with different sizes (not an ideal UI for this but it works for now). Eg you can do this by inputting "40 500000" for population size: 
![image](https://user-images.githubusercontent.com/6476455/36313496-810c1426-12e6-11e8-8c83-f10cc56e78db.png)

The text gets manipulated to a reactive numeric vector n() with the pop sizes evenly divided across populations in server.R. Instead of switching to numericInput, I pointed the validate statement to the max of the reactive numeric vector n() and bumped the maximum to 10,000,000.
